billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'

urlpatterns = [
	path('', views.home, name='home'),
	path('upload-design/', views.model_form_upload, name='model_form_upload'),
]

colon/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('billing/', include('billing.urls')),
    path('admin/', admin.site.urls),
    path('ecom/', include('ecom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('not-found-error/', views.show404, name='show404'),
    path('internal-server-error/', views.show500, name='show500'),
    path('shop/<pk>/', views.shop, name='shop'),
    path('my-cart/', views.cart, name='cart'),
    path('products-list/', views.products_all, name='products_all'),
    path('contact/', views.contact, name='contact'),
    path('specifications/', views.specific, name='specific'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('upload/', views.model_form_upload, name='model_form_upload'),
    path('order-success/', views.order_success, name='order_success'),
    path('contact-success/', views.contact_success, name='contact_success'),
]

billing/models.py
from django.db import models
from django.conf import settings
from ecom.models import Products, Cart


User = settings.AUTH_USER_MODEL

# Create your models here.
class Billings(models.Model):
	full_name = models.CharField(max_length = 100)
	email = models.EmailField(max_length=254)
	billing_addr = models.CharField(max_length=500)
	shipping_addr = models.CharField(max_length=500)
	pincode = models.IntegerField()
	phone_number = models.IntegerField()


class Content(models.Model):
    image = models.ImageField(upload_to = 'content/')
    name_of_item = models.CharField(max_length=300)


billing/forms.py
from .models import Billings, Content
from django import forms

class BillingForm(forms.ModelForm):
    full_name = forms.CharField(max_length = 100)
    email = forms.EmailField(max_length=254)
    billing_addr = forms.CharField(max_length=500)
    shipping_addr = forms.CharField(max_length=500)
    pincode = forms.IntegerField()
    phone_number = forms.IntegerField()
    
    class Meta:
        model = Billings
        fields = ('full_name', 'email', 'billing_addr','shipping_addr', 'pincode', 'phone_number')


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ('image', 'name_of_item')

billing/views.py
from django.shortcuts import render
from .forms import BillingForm, DocumentForm

# Create your views here.
def home(request):
    if request.method == 'POST':
        form = BillingForm(request.POST)
        if form.is_valid():
            bill = form.save()
            bill.refresh_from_db()
            bill.full_name = form.cleaned_data.get('full_name')
            bill.email = form.cleaned_data.get('email')
            bill.billing_addr = form.cleaned_data.get('billing_addr')
            bill.shipping_addr = form.cleaned_data.get('shipping_addr')
            bill.pincode = form.cleaned_data.get('pincode')
            bill.phone_number = form.cleaned_data.get('phone_number')
            bill.save()
            return redirect('order_success')
    else:
        form = BillingForm()
    return render(request, 'billing/home.html', {'form': form})

def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'upload_design.html', {
        'form': form
    })

templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<title>SKYWALKSFASHION | Home</title>
<meta charset="UTF-8">

<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://headervideo.github.io/hvheadervideo/css/fontawesome.min.css">
    <link href="https://headervideo.github.io/hvheadervideo/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/mdb.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/style.css" rel="stylesheet">
    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<style>
.w3-sidebar a {font-family: poppins;}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: poppins;}



/*******************************************************************************/


</style>
<body class="w3-content" style="background: #272824;">

<!-- Sidebar/menu -->
<nav class="w3-bar w3-border-bottom" style="background: #272824;">
  <a href="{% url 'home' %}"><div class="w3-bar-item w3-padding-14 w3-wide" style="color: #d4d9d1; font-weight: bolder; font-size: 20px; font-family: poppins;">SKYWALKSFASHION</div></a>
  <a href="{% url 'cart' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px; border-left: 1px solid #272824;"><i class="fa fa-shopping-cart w3-margin-right"></i></a>
  
 
  {% block navbar %}
  {% if user.is_authenticated %}
	<a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px; border-left: 1px solid #272824;">Logout</a>
  <a href="{% url 'billing:model_form_upload' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px; border-left: 1px solid #272824;">Upload Your Design</a>
  {% else %}
  	 <a href="{% url 'signup' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px;  border-left: 1px solid #272824;">Register</a>
	<a href="{% url 'login' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1;  margin-top: 3px;  border-left: 1px solid #272824;" >Login</a>
  {% endif %}
  {% endblock %} 
  <a href="{% url 'products_all' %}" class="w3-right w3-bar-item w3-button w3-mobile" style="color: #d4d9d1; margin-top: 3px;  border-left: 1px solid #272824;">
      <i class="fa fa-search"></i>
  </a>
</nav>

<!-- Top menu on small screens 
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>-->

<!-- Overlay effect when opening sidebar on small screens 
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
-->
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:0px; background: #272824;">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>
  
  <!-- Top header -->
  <div style="margin-top: 50px;"></div>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="{% static 'images/cover.jpg' %}" alt="Jeans" style="width:100%">
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small">New arrivals</h1>
      <h1 class="w3-hide-large w3-hide-medium">New arrivals</h1>
      <h1 class="w3-hide-small">COLLECTION 2018</h1>
      <p><a href="{% url 'products_all' %}" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>

{% block content %}
{% if user.is_authenticated %}
	<div style="margin-top: 50px; min-height: 600px; padding: 20%;" class="w3-container w3-black w3-padding-32" id="PRODUCTS">
	  <center><h2 style="color: #d4d9d1; font-weight: bolder; border-bottom: 2px solid red;">PRODUCTS</h2></center>
		<div style="margin-top: 100px;"></div>
<!-- -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
    
  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    
  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    
  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  
    </ol>
  
    <div class="carousel-inner">
    
  <div class="carousel-item active">

            <img class="d-block w-100" src="{% static 'images/product 1.jpg' %}" alt="First slide" style="width: 80%; height: 350px;">

        </div>

        <div class="carousel-item">
  
          <img class="d-block w-100" src="{% static 'images/product 2.jpg' %}" alt="Second slide" style="width: 80%; height: 350px;">

        </div>

        <div class="carousel-item">
  
          <img class="d-block w-100" src="{% static 'images/product 3.jpg' %}" alt="Third slide" style="width: 80%; height: 350px;">

        </div>

    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    
  <span class="sr-only">Previous</span>
  
    </a>
  
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">

        <span class="carousel-control-next-icon" aria-hidden="true"></span>
    
    <span class="sr-only">Next</span>

    </a>

</div>
<!-- -->
  <center><a href="{% url 'products_all' %}" class="w3-bar-item w3-button w3-mobile" style="border-radius: 6px; color: #d4d9d1; margin-top: 3px; border: 1px solid #d4d9d1;">Explore The Products</a></center>
	</div>
{% else %}
<div style="margin-top: 100px;"></div>
<center>
  <div style="margin-top: 50px; min-height: 300px; padding: 20%;" class="w3-container w3-black w3-padding-32" >
  	<p style="font-size: 22px; color: #d4d9d1; margin-top: 50px;">Dive into the World of Fashion</p>
   <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-mobile" style="border-radius: 6px; color: #d4d9d1; margin-top: 3px; border: 1px solid #d4d9d1;">login</a>
  </div>
</center>
 
{% endif %}
{% endblock %}

 
  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer" style="margin-top: 200px;">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        
        <h4>Contact</h4>
        <a href="{% url 'contact' %}" style="text-decoration: none;">
          <button type="submit" class="w3-button w3-block w3-black">Click her to contact the Seller</button>
        </a>
      </div>





      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="{% url 'show404' %}" style="text-decoration: none;" class="">About us</a></p>
        <p><a href="{% url 'show500' %}" style="text-decoration: none;" class="">Return</a></p>
        <p><a href="{% url 'show404' %}" style="text-decoration: none;" class="">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> SKYWALKFASHION</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> skywalkfashion@gmail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24" style="font-size: 11px;">&copy; 2018 | <a href="{% url 'home' %}" title="" target="_blank" class="w3-hover-opacity" style="text-decoration: none;">SKYWALKFASHION</a></div>

  <!-- End page content -->
</div>

<!-- Newsletter Modal -->
<div id="newsletter" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-center">
      <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
      <h2 class="w3-wide">NEWSLETTER</h2>
      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
      <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
      <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
    </div>

  </div>

  <!-- Subscribe section -->
  
</div>

<script>
// Accordion 
function myAccFunc() {
    var x = document.getElementById("demoAcc");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}
//////////////////////////////////////////////
</script>
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Latest compiled and minified CSS -->

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/my_cart.html
{% load static %}
<!DOCTYPE html>
<html>
<title>SKYWALKSFASHION | My Cart</title>
<meta charset="UTF-8">

<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://headervideo.github.io/hvheadervideo/css/fontawesome.min.css">
    <link href="https://headervideo.github.io/hvheadervideo/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/mdb.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/style.css" rel="stylesheet">
    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<style>
.w3-sidebar a {font-family: poppins;}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: poppins;}

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #fff;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #d4d9d1;
    color: rgba(0,0,0,0.9);
}
</style>
<body class="w3-content" style="background: #272824;">

<!-- Sidebar/menu -->
<nav class="w3-bar w3-border-bottom" style="background: #272824;">
  <a href="{% url 'home' %}"><div class="w3-bar-item w3-padding-14 w3-wide" style="color: #d4d9d1; font-weight: bolder; font-size: 20px; font-family: poppins;">SKYWALKSFASHION</div></a>
 
  
 
  {% block navbar %}
  {% if user.is_authenticated %}
	<a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px; border-left: 1px solid #272824;">Logout</a>
  {% else %}
  	 <a href="{% url 'signup' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1; margin-top: 3px;  border-left: 1px solid #272824;">Register</a>
	<a href="{% url 'login' %}" class="w3-bar-item w3-button w3-mobile w3-right" style="color: #d4d9d1;  margin-top: 3px;  border-left: 1px solid #272824;" >Login</a>
  {% endif %}
  {% endblock %} 
  <a href="{% url 'products_all' %}" class="w3-right w3-bar-item w3-button w3-mobile" style="color: #d4d9d1; margin-top: 3px;  border-left: 1px solid #272824;">
      <i class="fa fa-search"></i>
  </a>
</nav>

<!-- Top menu on small screens 
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>-->

<!-- Overlay effect when opening sidebar on small screens 
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
-->
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:0px; background: #272824;">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>
  
  <!-- Top header -->
  <div style="margin-top: 50px;"></div>

  <!-- Image header -->
{% block content %}
{% if user.is_authenticated %}
	<div style="margin-top: 50px; min-height: 700px; padding: 10%;" class="w3-container w3-black w3-padding-32" id="PRODUCTS">
		  <center><h2 style="color: #d4d9d1; font-weight: bolder; border-bottom: 2px solid red;">MY CART</h2></center>
		<div style="margin-top: 100px;"></div>
		  <div class="row">
        <div class="col-md-3 col-sm-12 col-xs-12" style="min-height: 200px; border-right: 1px solid #d4d9d1; padding: 0px 27px;">
            <img src="{{ product_image.url }}" style="width: 100%; border-radius: 7px;">
        </div>  

        <div class="col-md-9 col-sm-12 col-xs-12" style="min-height: 200px;">
          <table>
            <tr>
              <th>ID</th>
              <th>Product Name</th>
              <th>Type</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
            <tr>
              <td>{{ selected_product.id }}</td>
              <td>{{ product_title }}</td>
              <td>{{ product_item_type }}</td>
              <td>{{ product_quantity }}</td>
              <td>$ {{ selected_product_price }}</td>
            </tr>
          </table>
          <div class="row">
            <div style="float: left; margin-top: 50px; margin-right: 0px; min-height: 300px;" class="col-md-6 col-sm-12 col-xs-12">
              <a href="{% url 'billing:home' %}" class="w3-right w3-bar-item w3-button w3-mobile" style="color: #d4d9d1; text-decoration: none; border: 1px solid red; background: red; border-radius: 7px; margin-top: 120px; width: 100%">
                Proceed to Enter Billing Information
              </a>
            </div>
            <div style="float: left; margin-top: 50px; margin-right: 0px; min-height: 300px;" class="col-md-6 col-sm-12 col-xs-12">
              <p style="margin-bottom: 20px; float: left;">Discount Amount: <span style="color: teal; margin-left: 50px; margin-right: 50px; float: right;">$ {{ product_discount }}</span></p>
              <p style="margin-bottom: 20px; float: left;">Service Charges: <span style="color: teal; margin-left: 50px; margin-right: 50px; float: right;">$ {{ product_service_charge }}</span></p>
              <p style="margin-bottom: 20px; float: left;">Shipping Charges: <span style="color: teal; margin-left: 50px; margin-right: 50px; float: right;">$ {{ product_shipping_charge }}</span></p>
              <div style="border-bottom: 1px solid red; margin-top: 20px;"></div>

              <p style="margin-top: 20px; float: left;">Total Amount: <span style="color: teal; margin-left: 50px; margin-right: 50px; float: right;">$ {{ total }}</span></p>
            </div>
          </div>
        </div>
      </div>
		</div>
{% else %}
<div style="margin-top: 100px;"></div>
<center>
  <div style="margin-top: 50px; min-height: 300px; padding: 20%;" class="w3-container w3-black w3-padding-32" >
  	<p style="font-size: 22px; color: #d4d9d1; margin-top: 50px;">Dive into the World of Fashion</p>
   <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-mobile" style="border-radius: 6px; color: #d4d9d1; margin-top: 3px; border: 1px solid #d4d9d1;">login</a>
  </div>
</center>
 
{% endif %}
{% endblock %}

 
  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer" style="margin-top: 200px;">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        
        <h4>Contact</h4>
        <a href="{% url 'contact' %}" style="text-decoration: none;">
          <button type="submit" class="w3-button w3-block w3-black">Click her to contact the Seller</button>
        </a>
      </div>





      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="{% url 'show404' %}" style="text-decoration: none;" class="">About us</a></p>
        <p><a href="{% url 'show404' %}" style="text-decoration: none;" class="">Return</a></p>
        <p><a href="{% url 'show404' %}" style="text-decoration: none;" class="">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> SKYWALKSFASHION</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> skywalkfashion@gmail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24" style="font-size: 11px;">&copy; 2018 | <a href="{% url 'home' %}" title="" target="_blank" class="w3-hover-opacity" style="text-decoration: none;">SKYWALKSFASHION</a></div>

  <!-- End page content -->
</div>

<!-- Newsletter Modal -->
<div id="newsletter" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-center">
      <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
      <h2 class="w3-wide">NEWSLETTER</h2>
      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
      <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
      <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
    </div>

  </div>

  <!-- Subscribe section -->
  
</div>

<script>
// Accordion 
function myAccFunc() {
    var x = document.getElementById("demoAcc");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}
</script>

</body>
</html>